project:
  name: 'testapp'
  entry_point: 'main.py'
  lint:
    enabled: true
    ignore_errors: false
  static_typing:
    enabled: true
    ignore_errors: true

deployment:
  fast_deploy:
    always_push_code: false # if false, only push if project checksum changes
    always_check_venv: false
  run_on_finish: true
  exclude_artefact_file: '{{ cwd }}/.gitignore'
  local:
    project_path: '{{ cwd }}'
    tarball_path: '/tmp/{{ project.name }}_deploy_artefact.tar.gz'
  remote:
    project_path: '$HOME/projects/{{ project.name }}'
    tarball_path: '/tmp/{{ project.name }}_deploy_artefact.tar.gz'
    venv:
      use: true
      path: 'venv'
